Issue/confsrvdev 23885 fixing xss in 2 0 x
atlassian-forks/velocity-tools pull request #2
Opened 2023-06-21 17:35 UTC by ajaysharma2

confsrvdev 23885 Fixed xss
changing java 5 to java8

2023-06-22 01:34 UTC, rjatkins requested changes

2023-06-22 01:34 UTC, rjatkins commented on pom.xml
We also need to update the distributionManagement to point to
```
    <distributionManagement>
        <repository>
            <id>atlassian-3rdparty</id>
            <url>https://packages.atlassian.com/maven/3rdparty</url>
        </repository>
    </distributionManagement>
```

2023-06-22 01:34 UTC, rjatkins commented on src/main/java/org/apache/velocity/tools/view/VelocityViewServlet.java
> +            html.append(StringEscapeUtils.escapeHtml(ServletUtils.getPath(request)));
Require `ATLASSIAN:` comment before this, explaining what we changed

2023-06-22 01:34 UTC, rjatkins commented on src/test/java/org/apache/velocity/tools/test/blackbox/ViewToolsTests.java
Why was this test deleted?

2023-06-22 12:31 UTC, ajaysharma2 commented on src/test/java/org/apache/velocity/tools/test/blackbox/ViewToolsTests.java
In upstream also it is deleted, Also it needs sample project deployment for testing it
I am looking into it if can be restored and tested

2023-06-22 12:31 UTC, ajaysharma2 commented on pom.xml
Done

2023-07-06 11:56 UTC, rjatkins approved these changes
Looks good!

2023-07-06 11:56 UTC, merged